CSect   Symbol    Value     LENGTH    Flags:
-----------------------------------------
SUM               000000  002F0A
        TOTAL     002F04             R
        TABLE2    001794             R
        TABLE     000024             R
        COUNT     000021             R
        MYLIT     00001D             R
        LOOP      00000A             R
        FIRST     000000             R

Literal Table
Name      Operand     Address   Length:
-----------------------------------------------
EOF       454F46      002F07    3
